// artifacts/automotive/src/pages/CarDetail.tsx
import React, { useState } from "react";
import { useParams } from "wouter";
import { useGetCar, getGetCarQueryKey, useSubmitFinancingApplication, useListCars } from "@workspace/api-client-react";
import { Heart, MessageCircle, ChevronRight, Check } from "lucide-react";
import { Link } from "wouter";
import { useToast } from "@/hooks/use-toast";
import { CarCard } from "../components/CarCard";

export function CarDetail() {
  const { id } = useParams();
  const carId = Number(id);
  const { data: car, isLoading, error } = useGetCar(carId, { query: { enabled: !!carId, queryKey: getGetCarQueryKey(carId) } });
  const { data: similarCars = [] } = useListCars({ make: car?.make, limit: 3 });
  
  const submitFinancing = useSubmitFinancingApplication();
  const { toast } = useToast();

  const [form, setForm] = useState({ fullName: "", phone: "", email: "", downPayment: "", months: "36" });

  if (isLoading) return <div className="container mx-auto px-4 py-20 text-center">Loading...</div>;
  if (error || !car) return <div className="container mx-auto px-4 py-20 text-center">Car not found.</div>;

  const filteredSimilarCars = similarCars.filter(c => c.id !== carId).slice(0, 3);

  const handleApply = (e: React.FormEvent) => {
    e.preventDefault();
    submitFinancing.mutate(
      { data: { ...form, carId: car.id, downPayment: Number(form.downPayment), months: Number(form.months) } },
      {
        onSuccess: () => {
          toast({ title: "Application Submitted", description: "Our team will contact you shortly." });
          setForm({ fullName: "", phone: "", email: "", downPayment: "", months: "36" });
        },
        onError: () => {
          toast({ title: "Error", description: "Failed to submit application.", variant: "destructive" });
        }
      }
    );
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="text-sm text-muted-foreground mb-6 flex items-center gap-2">
        <Link href="/" className="hover:text-foreground">Home</Link> <ChevronRight className="w-3 h-3" />
        <Link href="/inventory" className="hover:text-foreground">Inventory</Link> <ChevronRight className="w-3 h-3" />
        <span className="text-foreground font-medium">{car.make} {car.model}</span>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-16">
        <div className="lg:col-span-2 space-y-8">
          <div className="aspect-[16/9] bg-secondary rounded-2xl overflow-hidden border border-border">
            <img src={car.imageUrl} alt={`${car.make} ${car.model}`} className="w-full h-full object-cover" />
          </div>

          <div>
            <h1 className="text-3xl font-bold text-foreground mb-2">{car.make} {car.model} {car.year}</h1>
            <p className="text-xl text-primary font-bold">${car.price.toLocaleString()}</p>
          </div>

          <div className="bg-card border border-border rounded-xl p-6">
            <h2 className="text-lg font-bold mb-4">Specifications</h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              <div><span className="text-muted-foreground text-sm">Mileage</span><p className="font-medium">{car.mileage.toLocaleString()} km</p></div>
              <div><span className="text-muted-foreground text-sm">Fuel Type</span><p className="font-medium">{car.fuelType}</p></div>
              <div><span className="text-muted-foreground text-sm">Transmission</span><p className="font-medium">{car.transmission}</p></div>
              <div><span className="text-muted-foreground text-sm">Body Type</span><p className="font-medium">{car.bodyType || 'N/A'}</p></div>
            </div>
            {car.description && (
              <div className="mt-6 pt-6 border-t border-border">
                <h3 className="font-bold mb-2">Description</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">{car.description}</p>
              </div>
            )}
          </div>
        </div>

        <div className="space-y-6">
          <div className="bg-card border border-border rounded-xl p-6 shadow-sm">
            <h2 className="text-lg font-bold mb-4">Interested?</h2>
            <div className="space-y-4">
              <a 
                href={`https://wa.me/971501234567?text=I'm interested in the ${car.make} ${car.model}`}
                target="_blank" rel="noopener noreferrer"
                className="w-full flex items-center justify-center gap-2 bg-[#25D366] hover:bg-[#20BD5A] text-white py-3 px-4 rounded-md font-medium transition-colors"
              >
                <MessageCircle className="w-5 h-5" /> Chat on WhatsApp
              </a>
              <button className="w-full flex items-center justify-center gap-2 border border-input bg-transparent hover:bg-secondary py-3 px-4 rounded-md font-medium transition-colors text-foreground">
                <Heart className="w-5 h-5" /> Save to Favorites
              </button>
            </div>
          </div>

          <div className="bg-card border border-border rounded-xl p-6 shadow-sm">
            <h2 className="text-lg font-bold mb-4">Apply for Financing</h2>
            <form onSubmit={handleApply} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">Full Name</label>
                <input required type="text" value={form.fullName} onChange={e => setForm({...form, fullName: e.target.value})} className="w-full border border-input rounded-md p-2 text-sm bg-background" />
              </div>
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">Phone Number</label>
                <input required type="tel" value={form.phone} onChange={e => setForm({...form, phone: e.target.value})} className="w-full border border-input rounded-md p-2 text-sm bg-background" />
              </div>
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">Down Payment ($)</label>
                <input required type="number" value={form.downPayment} onChange={e => setForm({...form, downPayment: e.target.value})} className="w-full border border-input rounded-md p-2 text-sm bg-background" />
              </div>
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">Term</label>
                <select value={form.months} onChange={e => setForm({...form, months: e.target.value})} className="w-full border border-input rounded-md p-2 text-sm bg-background">
                  <option value="12">12 Months</option>
                  <option value="24">24 Months</option>
                  <option value="36">36 Months</option>
                  <option value="48">48 Months</option>
                  <option value="60">60 Months</option>
                </select>
              </div>
              <button disabled={submitFinancing.isPending} type="submit" className="w-full bg-primary hover:bg-primary/90 text-primary-foreground py-3 rounded-md font-medium transition-colors">
                {submitFinancing.isPending ? "Submitting..." : "Submit Application"}
              </button>
            </form>
          </div>
        </div>
      </div>

      {filteredSimilarCars.length > 0 && (
        <div className="border-t border-border pt-12">
          <h2 className="text-2xl font-bold mb-6">Similar Vehicles</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {filteredSimilarCars.map(similarCar => (
              <CarCard key={similarCar.id} car={similarCar} />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// src/app/pages/car-detail.component.ts
import { CommonModule } from "@angular/common";
import { Component, OnInit, inject, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { ActivatedRoute, RouterLink } from "@angular/router";
import { ApiService } from "../api.service";
import { CarCardComponent } from "../components/car-card.component";
import type { Car } from "../models";

@Component({
  selector: "app-car-detail",
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, CarCardComponent],
  templateUrl: "./car-detail.component.html",
})
export class CarDetailComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly route = inject(ActivatedRoute);

  readonly car = signal<Car | undefined>(undefined);
  readonly similarCars = signal<Car[]>([]);
  readonly isLoading = signal(true);
  readonly message = signal("");
  readonly isSubmitting = signal(false);
  readonly form = {
    fullName: "",
    phone: "",
    email: "",
    downPayment: "",
    months: "36",
  };

  ngOnInit(): void {
    const id = Number(this.route.snapshot.paramMap.get("id"));
    this.api.getCar(id).subscribe((car) => {
      this.car.set(car);
      this.isLoading.set(false);
      if (car) {
        this.api.getCars({ make: car.make, limit: 3 }).subscribe((cars) => {
          this.similarCars.set(cars.filter((item) => item.id !== car.id).slice(0, 3));
        });
      }
    });
  }

  submit(): void {
    const car = this.car();
    if (!car) return;
    this.isSubmitting.set(true);
    this.api
      .submitFinancingApplication({
        carId: car.id,
        fullName: this.form.fullName,
        phone: this.form.phone,
        email: this.form.email,
        downPayment: Number(this.form.downPayment),
        months: Number(this.form.months),
      })
      .subscribe(() => {
        this.message.set("Application submitted. Our team will contact you shortly.");
        this.isSubmitting.set(false);
        this.form.fullName = "";
        this.form.phone = "";
        this.form.email = "";
        this.form.downPayment = "";
        this.form.months = "36";
      });
  }

  whatsappUrl(car: Car): string {
    return `https://wa.me/971501234567?text=${encodeURIComponent(`I'm interested in the ${car.make} ${car.model}`)}`;
  }
}

<div *ngIf="isLoading()" class="container mx-auto px-4 py-20 text-center">Loading...</div>
<div *ngIf="!isLoading() && !car()" class="container mx-auto px-4 py-20 text-center">Car not found.</div>

<div *ngIf="car() as vehicle" class="container mx-auto px-4 py-8">
  <div class="text-sm text-muted-foreground mb-6 flex items-center gap-2">
    <a routerLink="/" class="hover:text-foreground">Home</a>
    <span>›</span>
    <a routerLink="/inventory" class="hover:text-foreground">Inventory</a>
    <span>›</span>
    <span class="text-foreground font-medium">{{ vehicle.make }} {{ vehicle.model }}</span>
  </div>

  <div class="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-16">
    <div class="lg:col-span-2 space-y-8">
      <div class="aspect-[16/9] bg-secondary rounded-2xl overflow-hidden border border-border">
        <img [src]="vehicle.imageUrl" [alt]="vehicle.make + ' ' + vehicle.model" class="w-full h-full object-cover" />
      </div>
      <div>
        <h1 class="text-3xl font-bold text-foreground mb-2 font-display">{{ vehicle.make }} {{ vehicle.model }} {{ vehicle.year }}</h1>
        <p class="text-xl text-primary font-bold">{{ vehicle.type === "rent" ? "$" + vehicle.price + "/day" : "$" + (vehicle.price | number) }}</p>
      </div>
      <div class="bg-card border border-border rounded-xl p-6">
        <h2 class="text-lg font-bold mb-4">Specifications</h2>
        <div class="grid grid-cols-2 md:grid-cols-4 gap-6">
          <div><span class="spec-label">Mileage</span><p class="font-medium">{{ vehicle.mileage | number }} km</p></div>
          <div><span class="spec-label">Fuel Type</span><p class="font-medium">{{ vehicle.fuelType }}</p></div>
          <div><span class="spec-label">Transmission</span><p class="font-medium">{{ vehicle.transmission }}</p></div>
          <div><span class="spec-label">Body Type</span><p class="font-medium">{{ vehicle.bodyType || "N/A" }}</p></div>
        </div>
        <div *ngIf="vehicle.description" class="mt-6 pt-6 border-t border-border">
          <h3 class="font-bold mb-2">Description</h3>
          <p class="text-muted-foreground text-sm leading-relaxed">{{ vehicle.description }}</p>
        </div>
      </div>
    </div>

    <aside class="space-y-6">
      <div class="bg-card border border-border rounded-xl p-6 shadow-sm">
        <h2 class="text-lg font-bold mb-4">Interested?</h2>
        <div class="space-y-4">
          <a [href]="whatsappUrl(vehicle)" target="_blank" rel="noopener noreferrer" class="w-full flex items-center justify-center gap-2 bg-[#25D366] hover:bg-[#20BD5A] text-white py-3 px-4 rounded-md font-medium transition-colors">
            Chat on WhatsApp
          </a>
          <button type="button" class="w-full flex items-center justify-center gap-2 border border-input bg-transparent hover:bg-secondary py-3 px-4 rounded-md font-medium transition-colors text-foreground">
            Save to Favorites
          </button>
        </div>
      </div>

      <div class="bg-card border border-border rounded-xl p-6 shadow-sm">
        <h2 class="text-lg font-bold mb-4">Apply for Financing</h2>
        <form (ngSubmit)="submit()" class="space-y-4">
          <label class="form-label">Full Name<input required name="fullName" [(ngModel)]="form.fullName" class="form-input mt-1" /></label>
          <label class="form-label">Phone Number<input required type="tel" name="phone" [(ngModel)]="form.phone" class="form-input mt-1" /></label>
          <label class="form-label">Email<input type="email" name="email" [(ngModel)]="form.email" class="form-input mt-1" /></label>
          <label class="form-label">Down Payment ($)<input required type="number" name="downPayment" [(ngModel)]="form.downPayment" class="form-input mt-1" /></label>
          <label class="form-label">Term
            <select name="months" [(ngModel)]="form.months" class="form-input mt-1">
              <option value="12">12 Months</option>
              <option value="24">24 Months</option>
              <option value="36">36 Months</option>
              <option value="48">48 Months</option>
              <option value="60">60 Months</option>
            </select>
          </label>
          <button [disabled]="isSubmitting()" type="submit" class="w-full bg-primary hover:bg-primary/90 text-primary-foreground py-3 rounded-md font-medium transition-colors">
            {{ isSubmitting() ? "Submitting..." : "Submit Application" }}
          </button>
          <p *ngIf="message()" class="text-sm text-[#5C7C5A]">{{ message() }}</p>
        </form>
      </div>
    </aside>
  </div>

  <div *ngIf="similarCars().length > 0" class="border-t border-border pt-12">
    <h2 class="text-2xl font-bold mb-6 font-display">Similar Vehicles</h2>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
      <app-car-card *ngFor="let item of similarCars()" [car]="item" />
    </div>
  </div>
</div>
