// artifacts/automotive/src/components/StatCounter.tsx
import React, { useEffect, useRef, useState } from "react";

interface StatCounterProps {
  target: number;
  suffix?: string;
  duration?: number;
}

export function StatCounter({ target, suffix = "", duration = 1600 }: StatCounterProps) {
  const [count, setCount] = useState(0);
  const ref = useRef<HTMLDivElement>(null);
  const started = useRef(false);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !started.current) {
          started.current = true;
          const start = performance.now();
          const step = (now: number) => {
            const elapsed = now - start;
            const progress = Math.min(elapsed / duration, 1);
            // Ease out cubic
            const eased = 1 - Math.pow(1 - progress, 3);
            setCount(Math.round(eased * target));
            if (progress < 1) requestAnimationFrame(step);
          };
          requestAnimationFrame(step);
        }
      },
      { threshold: 0.5 }
    );

    observer.observe(el);
    return () => observer.disconnect();
  }, [target, duration]);

  return (
    <div ref={ref}>
      {count.toLocaleString()}
      {suffix}
    </div>
  );
}

// src/app/components/stat-counter.component.ts
import { CommonModule } from "@angular/common";
import { AfterViewInit, Component, ElementRef, Input, OnDestroy, ViewChild } from "@angular/core";

@Component({
  selector: "app-stat-counter",
  standalone: true,
  imports: [CommonModule],
  template: `<span #counter>{{ count.toLocaleString() }}{{ suffix }}</span>`,
})
export class StatCounterComponent implements AfterViewInit, OnDestroy {
  @Input() target = 0;
  @Input() suffix = "";
  @Input() duration = 1600;
  @ViewChild("counter", { static: true }) counter?: ElementRef<HTMLElement>;

  count = 0;
  private observer?: IntersectionObserver;
  private started = false;

  ngAfterViewInit(): void {
    this.observe();
  }

  ngOnDestroy(): void {
    this.observer?.disconnect();
  }

  private observe(): void {
    const element = this.counter?.nativeElement;
    if (!element || this.started) return;
    this.observer = new IntersectionObserver(
      ([entry]) => {
        if (!entry?.isIntersecting || this.started) return;
        this.started = true;
        const start = performance.now();
        const step = (now: number) => {
          const progress = Math.min((now - start) / this.duration, 1);
          const eased = 1 - Math.pow(1 - progress, 3);
          this.count = Math.round(eased * this.target);
          if (progress < 1) requestAnimationFrame(step);
        };
        requestAnimationFrame(step);
      },
      { threshold: 0.5 },
    );
    this.observer.observe(element);
  }
}
